import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onPrimaryContainer,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.blueGray900.withOpacity(0.72),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(21.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 15.fSize,
          fontFamily: 'Inria Sans',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.deepPurple600,
          fontSize: 40.fSize,
          fontFamily: 'Dancing Script',
          fontWeight: FontWeight.w500,
        ),
        displaySmall: TextStyle(
          color: appTheme.black90001,
          fontSize: 36.fSize,
          fontFamily: 'Kranky',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: appTheme.deepPurple600,
          fontSize: 32.fSize,
          fontFamily: 'Dancing Script',
          fontWeight: FontWeight.w500,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 24.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.deepPurple600,
          fontSize: 20.fSize,
          fontFamily: 'Inria Sans',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 16.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 15.fSize,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFCCB4E9),
    primaryContainer: Color(0XFF642FA9),
    secondary: Color(0XFF642FA9),
    secondaryContainer: Color(0XFFE3E6BC),
    tertiary: Color(0XFF642FA9),
    tertiaryContainer: Color(0XFFE3E6BC),

    // Background colors
    background: Color(0XFF642FA9),

    // Surface colors
    surface: Color(0XFF642FA9),
    surfaceTint: Color(0XFF4F1697),
    surfaceVariant: Color(0XFFE3E6BC),

    // Error colors
    error: Color(0XFF4F1697),
    errorContainer: Color(0XFF54A7DD),
    onError: Color(0X77F1F5BC),
    onErrorContainer: Color(0XFF4F1697),

    // On colors(text colors)
    onBackground: Color(0XFFFFFFFF),
    onInverseSurface: Color(0X77F1F5BC),
    onPrimary: Color(0XFF4F1697),
    onPrimaryContainer: Color(0XFFFFFFFF),
    onSecondary: Color(0XFFFFFFFF),
    onSecondaryContainer: Color(0XFF4F1697),
    onTertiary: Color(0XFFFFFFFF),
    onTertiaryContainer: Color(0XFF4F1697),

    // Other colors
    outline: Color(0XFF4F1697),
    outlineVariant: Color(0XFF642FA9),
    scrim: Color(0XFF642FA9),
    shadow: Color(0XFF4F1697),

    // Inverse colors
    inversePrimary: Color(0XFF642FA9),
    inverseSurface: Color(0XFF4F1697),

    // Pending colors
    onSurface: Color(0XFFFFFFFF),
    onSurfaceVariant: Color(0XFF4F1697),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF010101);
  Color get black90001 => Color(0XFF000000);

  // Blue
  Color get blue700 => Color(0XFF2685C3);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray900 => Color(0XFF292D32);

  // DeepOrange
  Color get deepOrange100 => Color(0XFFEDCBB7);
  Color get deepOrange100A8 => Color(0XA8FFB4B4);
  Color get deepOrangeA100 => Color(0XFFF69586);
  Color get deepOrangeA10066 => Color(0X66DEB27E);

  // DeepPurple
  Color get deepPurple600 => Color(0XFF652FA9);

  // Gray
  Color get gray50 => Color(0XFFF8F8F8);
  Color get gray700 => Color(0XFF606060);

  // GrayBc
  Color get gray50Bc => Color(0XBCF7F2FE);

  // GreenB
  Color get green300B2 => Color(0XB299B27F);

  // LightGreen
  Color get lightGreen100 => Color(0XFFDDFCB7);

  // Lime
  Color get lime900 => Color(0XFF935B44);

  // Red
  Color get red200 => Color(0XFFDE9292);

  // RedBa
  Color get red200Ba => Color(0XBAF99A9A);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
